version: 0.2

#env:
#  variables:
#    #IMAGE_CONFIG: "lambda_http_api"
#    #IMAGE_REPO_NAME: "quivr"
#    #IMAGE_TAG: "experimental"
#    #AWS_ACCOUNT_ID: "365024520127"
#    #AWS_DEFAULT_REGION: "us-west-2"

phases:
  install:
    commands:
      - cat /etc/issue
      - uname -a
      - whoami
      - pwd
      - apt update
      - apt -y install git
      - docker run hello-world
  pre_build:
    commands:
      - echo Clone PAIAssistant repo from Github...
      - git clone https://github.com/ShadNygren/quivr.git
      - echo Logging in to Amazon ECR...
      - #$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION
      - echo Build started on `date`
      - echo Building the Docker image...
      - IMAGE_CONFIG_LOWERCASE=$(echo $IMAGE_CONFIG | tr '[:upper:]' '[:lower:]')
      - IMAGE_REPO_NAME_LOWERCASE=$(echo $IMAGE_REPO_NAME | tr '[:upper:]' '[:lower:]')
      - IMAGE_TAG_LOWERCASE=$(echo $IMAGE_TAG | tr '[:upper:]' '[:lower:]')
      - #docker build -f Dockerfile.$IMAGE_CONFIG -t $IMAGE_REPO_NAME_LOWERCASE-$IMAGE_CONFIG_LOWERCASE:$IMAGE_TAG_LOWERCASE --build-arg AWS_ACCESS_KEY=$AWS_ACCESS_KEY --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_DEFAULT_REGION=AWS_DEFAULT_REGION .
      - docker compose pull
      - docker compose up
      - docker tag $IMAGE_REPO_NAME_LOWERCASE-$IMAGE_CONFIG_LOWERCASE:$IMAGE_TAG_LOWERCASE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_LOWERCASE-$IMAGE_CONFIG_LOWERCASE:$IMAGE_TAG_LOWERCASE
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_LOWERCASE-$IMAGE_CONFIG_LOWERCASE:$IMAGE_TAG_LOWERCASE
